from handclassifier import ManualTextClassifierSingle
from handclassifier import ManualBrowserClassifierSingle
from handclassifier import ManualWaybackClassifierSingle
from handclassifier import ManualWaybackPlusMongoDBClassifierSingle
